version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: love-elasticsearch
    restart: unless-stopped
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - elastic.env
    networks:
      - elk
  kibana:
    image: kibana:7.17.1
    container_name: love-kibana
    restart: unless-stopped
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
