version: '3.3'
services:
  love-zabbix-server:
    image: zabbix/zabbix-server-mysql:5.0.36-ubuntu
    container_name: love-zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - zabbix.env
    dns:
      - 8.8.8.8
      - 172.16.12.4
    networks:
      default:
        ipv4_address: 172.18.0.2
  love-grafana-server:
    image: grafana/grafana:7.5.17-ubuntu
    container_name: love-grafana-server
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    env_file:
      - grafana.env
    networks:
      default:
        ipv4_address: 172.18.0.3
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
