version: '3.9'
services:
  love-zabbix-server:
    image: zabbix/zabbix-server-mysql:5.0-ubuntu-latest
    container_name: love-zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - zabbix.env
    networks:
      default:
        ipv4_address: 172.28.0.254
  love-grafana-server:
    image: grafana/grafana:7.5.17-ubuntu
    container_name: love-grafana-server
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    env_file:
      - grafana.env
    networks:
     default:
       ipv4_address: 172.28.0.252
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16         
