---
- name: Download zabbix repo package
  get_url:
    url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    dest: /tmp/zabbix-release_5.0-1+focal_all.deb

- name: Install zabbix repo
  apt:
    deb: /tmp/zabbix-release_5.0-1+focal_all.deb
    state: present

- name: Install zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes
