---
- name: Copy rpm file to server
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent-5.0.34-1.el7.x86_64.rpm
    dest: /tmp/zabbix-agent-5.0.34-1.el7.x86_64.rpm
- name: Install zabbix-agent centos
  yum: 
    name: /tmp/zabbix-agent-5.0.34-1.el7.x86_64.rpm
    state: present
