---
- hosts: web
  become: true
  tasks:
    - name: Install Bind
      package:
        name: bind9 
        state: present
      notify:
        - bind systemd
  handlers:
    - name: bind systemd
      systemd:
        name: bind9
        enabled: yes
        state: started
